version: '3.8'

services:
  db:
    image: postgres:13
    container_name: clinic-management-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - clinic-net

volumes:
  pgdata:
    driver: local

networks:
  clinic-net:
    driver: bridge